[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.3",
    "langgraph>=0.6.10",
    "sqlmodel>=0.0.27",
    "uvicorn>=0.37.0",
]
